name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Testing
    env:
      SERVER: ${{ secrets.SERVER }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}
      DOMAIN: ${{ secrets.DOMAIN }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # or your version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run NUnit tests
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
